model: openrouter/deepseek/deepseek-r1
editor-model: openrouter/anthropic/claude-3.5-sonnet
architect: true

auto-commits: false
dirty-commits: false
attribute-author: false
attribute-committer: false
gitignore: false

dark-mode: true
check-update: false
show-release-notes: false
analytics: false
