[project]
name = "python-template"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
python-template = "python_template:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
